### ISSUE TITLE
Can we get the updated map 4.4d please ?

### ISSUE THREAD

**Issue by gjvdheuvel** [CypherMediaGIT/DayZCommunityOfflineMode-DeerIsle-Edition#1]
Can we get the updated map 4.4d please ? Would be super cool :)
Official Map downlaod announced and made available here: https://mega.nz/file/KbhXHSLa#cHHChjiaXguubjom0yVbLHJQzGapC4K-ZPmJf46VlVs

**Comment by CypherMediaGIT** [comment]
I will do this soon, but you won’t see changes until the Map update is released on the 16th Feb

**Comment by StarLuft** [comment]
is it updated to 4.4? please do update if possible

**Comment by CypherMediaGIT** [comment]
this has now been released!!
